Bestinja.FronEnd.MVC/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Bestinja.Services;
using Bestinja.Services.Contract;
using BestInja.Model;
using Microsoft.AspNet.Identity;
using Westwind.Web.Mvc;

namespace Bestinja.FronEnd.MVC.Controllers
{
    //[Authorize]
    public class ProfilesController : Controller
    {
        private readonly IProfileService _profileService;
        private readonly IServiceImageService _imageService;

        public ProfilesController()
        {
            _profileService = new ProfileService();
            _imageService = new ServiceImageService();
        }

        // GET: Profile
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();

            var services = await _profileService.GetUserService(new Guid(userId));

            return View(services);
        }

        public async Task<ActionResult> _Gallery(Guid id)
        {
            var serviceImages = await _imageService.ServiceImages(id);
            ViewBag.ServiceId = id;
            return View(serviceImages);
        }
        [HttpPost]
        public ActionResult Upload()
        {

            if (Request.Files.Count > 0)
            {

                FileUpload(Request.Files);
            }
            return null;
        }

        public ActionResult UploadToServer(Guid serviceId)
        {
            try
            {


                List<ImageDto> addImageDtos = new List<ImageDto>();
                var tempFolder = $"~/Temporary/{User.Identity.GetUserId()}";
                var destinationFolder = $"~/Images/vendor/{User.Identity.GetUserId()}/org";
                var destinationFolderthumb = $"~/Images/vendor/{User.Identity.GetUserId()}/thumb";

                if (!Directory.Exists(Server.MapPath(destinationFolder)))
                {
                    Directory.CreateDirectory(Server.MapPath(destinationFolder));
                    Directory.CreateDirectory(Server.MapPath(destinationFolderthumb));

                }


                var sourceFiles = Directory.GetFiles(Server.MapPath(tempFolder));
                foreach (string file in sourceFiles)
                {
                    FileInfo mFile = new FileInfo(file);
                    // to remove name collisions
                    if (new FileInfo(Server.MapPath(destinationFolder) + "\\" + mFile.Name).Exists == false)
                    {

                        mFile.MoveTo(Server.MapPath(destinationFolder) + "\\" + mFile.Name);


                    }
                    Size.ResizeImage(Server.MapPath(destinationFolder) + "\\" + mFile.Name,
                                            Server.MapPath(destinationFolderthumb + "\\" + mFile.Name),
                                            ImageFormat.Jpeg, 150, 200);
                    addImageDtos.Add(new ImageDto()
                    {
                        Url = $"{destinationFolder}/{mFile.Name}",
                        ThumbUrl = $"{destinationFolderthumb}/{mFile.Name}",
                        Size = mFile.Length,
                        Title = mFile.Name,
                        ServiceId = serviceId
                    });
                }

                _imageService.AddServiceImages(addImageDtos);
                Directory.Delete(Server.MapPath(tempFolder), true);


                return Json(1, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                return Json(0, JsonRequestBehavior.AllowGet);

            }
        }

        public ActionResult DeleteImage(int id)
        {
            _imageService.RemoveImageFromGallery(id);
            return Json(1, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteFile(string fileName)
        {
            string root = "~/Temporary/";

            string path = $"{root}{ User.Identity.GetUserId()}/{fileName}";
            var url = Path.Combine(Server.MapPath(path));

            if (System.IO.File.Exists(url))
                System.IO.File.Delete(url);

            return null;
        }

        private List<string> FileUpload(HttpFileCollectionBase mainImage)
        {
            List<string> addressList = new List<string>();
            string root = "~/Temporary/";

            string path = $"{root}{ User.Identity.GetUserId()}/";
            string directory = $"{root}{User.Identity.GetUserId()}";

            Directory.CreateDirectory(Server.MapPath(directory));
            SaveFileToDirectory(mainImage, addressList, path);

            return addressList;


        }



        private void SaveFileToDirectory(HttpFileCollectionBase mainImage, List<string> addressList, string path)
        {
            for (int i = 0; i < mainImage.Count; i++)
            {
                var image = Image.FromStream(mainImage[i].InputStream, true, true);
                string trailingPath = Path.GetFileName(mainImage[i]?.FileName);
                string fullPath = Path.Combine(Server.MapPath(path), trailingPath);
                CompressImage(image, ImageFormat.Jpeg, 750, 550, fullPath);

                addressList.Add($"{path}{ mainImage[i]?.FileName}");

            }
        }

        private void CompressImage(Image img, ImageFormat format, int width, int height, string address)
        {
            Image thumbNail = new Bitmap(width, height, img.PixelFormat);
            Graphics g = Graphics.FromImage(thumbNail);
            g.CompositingQuality = CompositingQuality.HighQuality;
            g.SmoothingMode = SmoothingMode.HighQuality;
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Rectangle rect = new Rectangle(0, 0, width, height);
            g.DrawImage(img, rect);
            thumbNail.Save(address, format);
        }

        private void CheckAndCreateDirectory(string directory)
        {


        }
    }


    public class Size
    {
        public static bool ResizeImage(string orgFile, string resizedFile, ImageFormat format, int width, int height)
        {
            try
            {

                using (Image img = Image.FromFile(orgFile))
                {
                    Image thumbNail = new Bitmap(width, height, img.PixelFormat);
                    Graphics g = Graphics.FromImage(thumbNail);
                    g.CompositingQuality = CompositingQuality.HighQuality;
                    g.SmoothingMode = SmoothingMode.HighQuality;
                    g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                    Rectangle rect = new Rectangle(0, 0, width, height);
                    g.DrawImage(img, rect);
                    thumbNail.Save(resizedFile, format);
                }

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

    }

}

Bestinja.FronEnd.MVC/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Bestinja.Services;
using Bestinja.Services.Contract;
using BestInja.Model.Vendor;
using Westwind.Web.Mvc;

namespace Bestinja.FronEnd.MVC.Controllers
{
    [Authorize]
    public class VendorController : Controller
    {
        private readonly IVendorService _vendorService;

        public VendorController()
        {
            _vendorService = new VendorService();
        }
        // GET: Vendor
        public ActionResult AddVendor()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> AddVendor(AddVendorModel model, HttpPostedFileBase mainImage)
        {

            if (!ModelState.IsValid)
                return View(model);

            model.MainImage = FileUpload(model.Title, "vendor", mainImage);
            await _vendorService.AddVendor(model);
            return RedirectToAction("Index","Profiles");
        }

        public async Task<ActionResult> EditVendor(Guid vendorId)
        {
            var vendor =await _vendorService.GetService(vendorId);
            ViewBag.Checked = vendor.Facility.Select(x => x.Id).ToList();
            ViewBag.Facilites =await _vendorService.GetFacilities();
            return View(vendor);
        }
        public ActionResult MapTest()
        {
            return View();
        }

        public async Task<ActionResult> _Facility()
        {

            var facilities = await _vendorService.GetFacilities();

            string postsHtml = ViewRenderer.RenderPartialView("~/views/vendor/_Facility.cshtml", facilities);

            return Json(postsHtml, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetCategroy()
        {

            var category = await _vendorService.GetCategory();
            return Json(category, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FormLoad(int categroyId)
        {
            string postsHtml = ViewRenderer.RenderPartialView("~/views/vendor/_RegisterBody.cshtml");
            return Json(postsHtml, JsonRequestBehavior.AllowGet);

        }

        public ActionResult LoadScript()
        {
            string scritps = ViewRenderer.RenderPartialView("~/views/vendor/_RegisterBodyScript.cshtml");

            return Json(scritps, JsonRequestBehavior.AllowGet);

        }

            private string FileUpload(string title, string serviceType, HttpPostedFileBase mainImage)
            {

                string path = $"~/Images/{serviceType}/" + title + "/";
                string directory = $"~/Images/{serviceType}/" + title;

                if (mainImage != null)
                {

                    Directory.CreateDirectory(Server.MapPath(directory));
                    mainImage.SaveAs(Path.Combine(Server.MapPath(path), DateTime.Now.ToString("yyyy_MM_dd_mm_ss") + "_" + mainImage.FileName));
                    return $"{path}{mainImage.FileName}";
                }

                return null;
            }

    }
}

Bestinja.FronEnd.MVC/Views/Profiles/Index.cshtml
@model IEnumerable<BestInja.Model.Vendor.VendorListDto>
@{
    ViewBag.Title = "پروفایل";
    Layout = "../../Views/Shared/_Layout.cshtml";
}

<div class="container mgt140">

    <div class="row">
     
        <!--Start AdminSideBar-->
        @Html.Partial("_SidebarLinks")
        <!--  AdminSideBar-->
        <!--Start AdminLeftSection-->
        <div class="col-md-9">
            <div class="AdminContent">
                @Html.Partial("_ServiceList",Model)
            </div>
        </div>
        <!--End AdminLeftSection-->

    </div>
</div>
@section scripts
{
  
    @*<script>
        function getImges(id) {
            //ToDo appear loading
            $.ajax({
                url: "/Profile/_gallery",
                data: { id: id },
                contentType: 'application/json',
                success: function (data) {
                    $(".AdminContent").empty();
                    $(".AdminContent").append(data);

                }, error() {
                    alert("خطا در دریافت اطلاعات");
                }
            });
        }


      
    </script>*@
    
}
@section styles
{
<style>
   

    .tile {
        width: 50em;
        margin: 25px;
        height: 12em;
        position: relative;
        overflow: hidden;
        border-radius: 0.8em;
        box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.4);
    }

    .tile-img{
        background-size: cover;
        background-position: center center;
        background-repeat: none;
        width: inherit;
        height: inherit;
    }

    .tile-info {
        position: absolute;
        top: 0;
        left: 0;
        color: white;
        padding: 1em;
    }

   

    /* You can ignore anything below this. It does not contribute to the codepen in anyway, It's just so I can center the codepen when it displays and make it look pretty :D */

</style>

}

Bestinja.FronEnd.MVC/Views/Profiles/_Gallery.cshtml
@model IEnumerable<BestInja.Model.ImageDto>
<div class="container mgt140">

    <div class="row">
        @Html.Partial("_SidebarLinks")

        <div class="col-md-9">
            <div class="AdminContent">

                <!--Start Upload-->
                <section class="AdminNews AdminContentSection">
                    <h2>آپلود تصاویر</h2>
                    <p>توجه: تصاویر شما پس از تایید مدیریت در سایت نمایش داده میشود</p>
                    <form>
                        <div class="UploadSection">

                            <input type="file"
                                   class="filepond"
                                   name="filepond"
                                   multiple
                                   data-max-file-size="3MB"
                                   data-max-files="3">
                            <span class='lblUploadText' id="upload-file-info"></span>
                        </div>

                        <div class="FormElement cf">
                            <a href="#" onclick="SendImageToServer('@ViewBag.ServiceId',this);" class="btnCustom pull-left btnOrange"><i class="fa fa-save"></i><span>ذخیره تصاویر</span></a>
                        </div>
                    </form>
                    <hr>
                </section>
                <!--End Upload-->
                <section class="AdminNews AdminContentSection">
                    <h2>لیست تصاویر</h2>
                    <p>شما میتوانید تصاویر خود را از این بخش حذف کنید</p>
                    <ul class="lstImageThumb">
                        @foreach (var item in Model)
                        {
                            <li id="@item.Id">
                                <div class="imgThumbnail">
                                    <a class="btnRemoveThumb btn-confirm" data-id="@item.Id" href="#0"><i class="fa fa-close"></i></a>
                                    <img src="@Url.Content(item.ThumbUrl)" class="img-responsive" alt="">
                                </div>
                                @if (item.Status)
                                {
                                    <span class="imgStatus imgAccept bgGreen">
                                        <i class="fa fa-check"></i>
                                        تایید شده
                                    </span>
                                }
                                else
                                {
                                    <span class="imgStatus imgAccept bgGreen">
                                        <i class="fa fa-check"></i>
                                        در انتظار تایید
                                    </span>
                                }

                            </li>
                        }

                    </ul>
                </section>

            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">قصد حذف این تصویر را دارید</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="modal-btn-si">بله</button>
                <button type="button" class="btn btn-primary" id="modal-btn-no">خیر</button>
            </div>
        </div>
    </div>
</div>

@section styles{
    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
    <style>
        /*
        * FilePond Custom Styles
        */

        .filepond--drop-label {
            color: #4c4e53;
        }

        .filepond--label-action {
            text-decoration-color: #babdc0;
        }

        .filepond--panel-root {
            background-color: #edf0f4;
        }


        .filepond--root {
            width: 170px;
            margin: 0 auto;
        }
    </style>
}
@section scriptsfilepond
{
    <script src="https://unpkg.com/filepond-plugin-image-validate-size/dist/filepond-plugin-image-validate-size.js"></script>


    <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>

    <script src="https://unpkg.com/filepond/dist/filepond.js"></script>


    <!-- Turn all file input elements into ponds -->
    <script>

        FilePond.registerPlugin(
            FilePondPluginImagePreview,
            FilePondPluginImageValidateSize

        );

        // Select the file input and use
        // create() to turn it into a pond
        FilePond.create(document.querySelector('.filepond'),{
            imagePreviewMaxHeight: 256,
            imagePreviewMinHeight:44,
            allowImageValidateSize: true,
            imagePreviewMaxFileSize:500,
            imageValidateSizeLabelImageSizeTooBig:"حجم تصاویر وارد شده بیش از حد مجاز است"
        });
        FilePond.setOptions({
            server: {
                process: {
                    method: 'POST',
                    url: '/Profiles/Upload',
                    withCredentials: false,
                    headers: {},
                    timeout: 7000,
                    onload: function (data) {

                        $(".filepond--action-revert-item-processing").one('click',
                            function (e) {
                                var fileValue = $($(this).closest('.filepond--file-wrapper')[0]).find('legend').text();
                                $.ajax({
                                    url: '/Profiles/DeleteFile',
                                    data: { fileName: fileValue },

                                });
                            });
                    },
                    onerror: function () {
                        alert("error");
                    },
                    ondata: null
                }
            }
        });


        function SendImageToServer(serviceId) {
            $(event).css('pointer-events', 'none');
            $.ajax({
                url: "/Profiles/UploadToServer",
                data: { serviceId: serviceId },
                success: function (data) {
                    if (data == 1) {
                        setTimeout(function () {
                            location.reload();
                        }, 1500);
                    }
                }, error: function () {
                    alert("خطا در ذخیره تصاویر");
                }
            });
        }

        var modalConfirm = function (callback) {
            var id;
            $(".btn-confirm").on("click", function () {
                $("#mi-modal").modal('show');
                id = $(this).attr('data-id');
            });

            $("#modal-btn-si").on("click", function () {
                callback(true, id);
                $("#mi-modal").modal('hide');
            });

            $("#modal-btn-no").on("click", function () {
                callback(false, id);
                $("#mi-modal").modal('hide');
            });
        };

        modalConfirm(function (confirm, imageId) {
            if (confirm) {
                //Acciones si el usuario confirma
                $.ajax({
                    url: "/Profiles/DeleteImage",
                    data: { id: imageId },
                    type: "get",
                    success: function () {
                        $("li#" + imageId).remove();
                    }, error: function () {
                        alert("خطا در انجام عملیات");
                    }
                })
            } else {
                //Acciones si el usuario no confirma

            }
        });
        setTimeout(function () {
            $(".filepond--drop-label>label").css("font-size", "15px").html("آپلود تصاویر");
        },
            100);

    </script>
}

Bestinja.FronEnd.MVC/Views/Profiles/_NotificationList.cshtml
<section class="AdminNews AdminContentSection">
    <h2>اطلاعیه ها</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>عنوان</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td><a href="#">راه اندازی سایت عروسی</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td><a href="#">راه اندازی سایت عروسی</a></td>
            </tr>
            <tr>
                <td>3</td>
                <td><a href="#">راه اندازی سایت عروسی</a></td>
            </tr>
            <tr>
                <td>4</td>
                <td><a href="#">راه اندازی سایت عروسی</a></td>
            </tr>
            </tbody>
        </table>
    </div>
</section>

Bestinja.FronEnd.MVC/Views/Profiles/_ServiceList.cshtml
@model IEnumerable<BestInja.Model.Vendor.VendorListDto>

<a class="btn btn-success" href="@Url.Action("AddVendor","Vendor")">ثبت سرویس</a>


@foreach (var item in Model)
{
<div class='tile'>

    <div class='tile-info'>
        <div class="col-md-12">
            <div class="bg-danger col-md-4">
                <a href="@Url.Action("_Gallery",new{id=@item.Id})" class="btn btn-primary center">گالری تصاویر</a>
            </div>
            <div class="bg-danger col-md-4">
                <p>@item.Title</p>
               <p>@item.ServiceState</p>
            </div>
            <div class="bg-danger col-md-4">
                @*<img src="@Url.Content(item.MainImage)"/>*@
            </div>
        </div>
    </div>
</div>
}

Bestinja.FronEnd.MVC/Views/Profiles/_SidebarLinks.cshtml
 <div class="col-md-3 hidden-xs">
    <section class="AdminSideBar">
        <ul class="lstAdminSideBar">
            <li class="active"><a href="dashboard.htm"><i class="fa fa-dashboard"></i><span>داشبورد</span></a></li>
            <li><a href="#"><i class="fa fa-bell"></i><span>اعلانات</span><span class="NotificationCounter">12</span></a></li>
            <li><a href="list.htm"><i class="fa fa-list-ul"></i><span>لیست سرویس ها</span></a></li>
            <li><a href="#"><i class="fa fa-image"></i><span>مدیریت تصاویر</span></a></li>
            <li><a href="#"><i class="fa fa-envelope"></i><span>مرکز پیام</span></a></li>
        </ul>
    </section>
</div>