Bestinja.FronEnd.MVC/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Bestinja.Services;
using Bestinja.Services.Contract;
using BestInja.Model;
using Microsoft.AspNet.Identity;
using Westwind.Web.Mvc;

namespace Bestinja.FronEnd.MVC.Controllers
{
    //[Authorize]
    public class ProfilesController : Controller
    {
        private readonly IProfileService _profileService;
        private readonly IServiceImageService _imageService;

        public ProfilesController()
        {
            _profileService = new ProfileService();
            _imageService = new ServiceImageService();
        }

        // GET: Profile
        public async Task<ActionResult> Index()
        {
            var userId = User.Identity.GetUserId();

            var services = await _profileService.GetUserService(new Guid(userId));

            return View(services);
        }

        public async Task<ActionResult> _Gallery(Guid id)
        {
            var serviceImages = await _imageService.ServiceImages(id);
            ViewBag.ServiceId = id;
            return View(serviceImages);
        }
        [HttpPost]
        public ActionResult Upload()
        {

            if (Request.Files.Count > 0)
            {

                FileUpload(Request.Files);
            }
            return null;
        }

        public ActionResult UploadToServer(Guid serviceId)
        {
            try
            {


                List<ImageDto> addImageDtos = new List<ImageDto>();
                var tempFolder = $"~/Temporary/{User.Identity.GetUserId()}";
                var destinationFolder = $"~/Images/vendor/{User.Identity.GetUserId()}/org";
                var destinationFolderthumb = $"~/Images/vendor/{User.Identity.GetUserId()}/thumb";

                if (!Directory.Exists(Server.MapPath(destinationFolder)))
                {
                    Directory.CreateDirectory(Server.MapPath(destinationFolder));
                    Directory.CreateDirectory(Server.MapPath(destinationFolderthumb));

                }


                var sourceFiles = Directory.GetFiles(Server.MapPath(tempFolder));
                foreach (string file in sourceFiles)
                {
                    FileInfo mFile = new FileInfo(file);
                    // to remove name collisions
                    if (new FileInfo(Server.MapPath(destinationFolder) + "\\" + mFile.Name).Exists == false)
                    {

                        mFile.MoveTo(Server.MapPath(destinationFolder) + "\\" + mFile.Name);


                    }
                    Size.ResizeImage(Server.MapPath(destinationFolder) + "\\" + mFile.Name,
                                            Server.MapPath(destinationFolderthumb + "\\" + mFile.Name),
                                            ImageFormat.Jpeg, 150, 200);
                    addImageDtos.Add(new ImageDto()
                    {
                        Url = $"{destinationFolder}/{mFile.Name}",
                        ThumbUrl = $"{destinationFolderthumb}/{mFile.Name}",
                        Size = mFile.Length,
                        Title = mFile.Name,
                        ServiceId = serviceId
                    });
                }

                _imageService.AddServiceImages(addImageDtos);
                Directory.Delete(Server.MapPath(tempFolder), true);


                return Json(1, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                return Json(0, JsonRequestBehavior.AllowGet);

            }
        }

        public ActionResult DeleteImage(int id)
        {
            _imageService.RemoveImageFromGallery(id);
            return Json(1, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteFile(string fileName)
        {
            string root = "~/Temporary/";

            string path = $"{root}{ User.Identity.GetUserId()}/{fileName}";
            var url = Path.Combine(Server.MapPath(path));

            if (System.IO.File.Exists(url))
                System.IO.File.Delete(url);

            return null;
        }

        private List<string> FileUpload(HttpFileCollectionBase mainImage)
        {
            List<string> addressList = new List<string>();
            string root = "~/Temporary/";

            string path = $"{root}{ User.Identity.GetUserId()}/";
            string directory = $"{root}{User.Identity.GetUserId()}";

            Directory.CreateDirectory(Server.MapPath(directory));
            SaveFileToDirectory(mainImage, addressList, path);

            return addressList;


        }



        private void SaveFileToDirectory(HttpFileCollectionBase mainImage, List<string> addressList, string path)
        {
            for (int i = 0; i < mainImage.Count; i++)
            {
                var image = Image.FromStream(mainImage[i].InputStream, true, true);
                string trailingPath = Path.GetFileName(mainImage[i]?.FileName);
                string fullPath = Path.Combine(Server.MapPath(path), trailingPath);
                CompressImage(image, ImageFormat.Jpeg, 750, 550, fullPath);

                addressList.Add($"{path}{ mainImage[i]?.FileName}");

            }
        }

        private void CompressImage(Image img, ImageFormat format, int width, int height, string address)
        {
            Image thumbNail = new Bitmap(width, height, img.PixelFormat);
            Graphics g = Graphics.FromImage(thumbNail);
            g.CompositingQuality = CompositingQuality.HighQuality;
            g.SmoothingMode = SmoothingMode.HighQuality;
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            Rectangle rect = new Rectangle(0, 0, width, height);
            g.DrawImage(img, rect);
            thumbNail.Save(address, format);
        }

        private void CheckAndCreateDirectory(string directory)
        {


        }
    }


    public class Size
    {
        public static bool ResizeImage(string orgFile, string resizedFile, ImageFormat format, int width, int height)
        {
            try
            {

                using (Image img = Image.FromFile(orgFile))
                {
                    Image thumbNail = new Bitmap(width, height, img.PixelFormat);
                    Graphics g = Graphics.FromImage(thumbNail);
                    g.CompositingQuality = CompositingQuality.HighQuality;
                    g.SmoothingMode = SmoothingMode.HighQuality;
                    g.InterpolationMode = InterpolationMode.HighQualityBicubic;
                    Rectangle rect = new Rectangle(0, 0, width, height);
                    g.DrawImage(img, rect);
                    thumbNail.Save(resizedFile, format);
                }

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

    }

}

Bestinja.FronEnd.MVC/Views/Shared/_Footer.cshtml
<footer class="container-fluid bgFooter">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="FooterLink">
                    <span class="FooterLinkTitle">لینک های مفید</span>
                    <ul>
                        <li><a href="#">صفحه اصلی</a></li>
                        <li><a href="#">درباره ما</a></li>
                        <li><a href="#">تماس با ما</a></li>
                        <li><a href="#">گالری</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-5">
                <div class="FooterLink">
                    <span class="FooterLinkTitle">آخرین های بلاگ</span>
                    <ul>
                        <li><a href="#">آموزش ساخت پروفایل در سایت عروسی 24</a></li>
                        <li><a href="#">راه اندازی بخش اسلایدر در سایت</a></li>
                        <li><a href="#">160 تالار جدید به سایت اضافه شد</a></li>
                        <li><a href="#">برنده جشنواره ایران وب در سال 97</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="FooterLink">
                    <span class="FooterLinkTitle">درباره ما بیشتر بدانید</span>
                    <p>
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

Bestinja.FronEnd.MVC/Views/Shared/_Header.cshtml
<header class="FixedHeader">
    <!--Start TopBar-->
    <div id="TopBar" class="TopHeader">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <div class="TopBarLinks">
                        <ul class="lstTopBarLinks">
                            <li><a href="#">صفحه اصلی</a></li>
                            <li><a href="#">درباره ما</a></li>
                            <li><a href="#">گالری تصاویر</a></li>
                            <li><a href="#">تماس با ما</a></li>
                            <li><a href="#">راهنما</a></li>
                        </ul>
                    </div>
                </div>
                @if (!User.Identity.IsAuthenticated)
                {
                    <div class="col-md-2">
                        <span>
                            <a class="topRegister" data-toggle="modal" href="javascript:void(0)" onclick="openRegisterModal();"><i class="fa fa-plus"></i><span>ثبت تالار</span></a>
                        </span>
                    </div>
                }
                else
                {
                    <div class="col-md-2">
                        <section class="UserProfileSection">
                            <ul class="lstUserProfile MobileCenterItem">
                                <li>
                                    <a href="#"><i class="fa fa-angle-down"></i> <span>پنل کاربری</span></a>
                                    <ul>
                                        <li><a href="/Profiles/Index"><i class="fa fa-user"></i><span>پروفایل</span></a></li>
                                        <li><a href="@Url.Action("Index","Profiles")"><i class="fa fa-key"></i><span>تغییر رمز</span></a></li>
                                        <li><a href="@Url.Action("IdentitySignout","Home")" ><i class="fa fa-sign-out"></i><span>خروج</span></a></li>
                                    </ul>
                                </li>
                              
                            </ul>
                        </section>
                    </div>
                }

            </div>
        </div>
    </div>
    <!--End TopBar-->
    <!--Start TopMenu-->
    <div class="container-fluid bgTopMenu">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="TopMenu">
                        <ul id="MenuTop" class="lstTopMenu">
                            <li>
                                <a href="#">خانه</a>
                            </li>
                            <li>
                                <a href="#">خدمات</a>
                                <ul>
                                    <li>
                                        <a href="#">تالار عروسی</a>
                                        <ul>
                                            <li><a href="#">گزینه سطح سوم</a></li>
                                            <li><a href="#">گزینه سطح چهارم</a></li>
                                            <li><a href="#">گزینه سطح پنجم</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">ماشین عروس</a></li>
                                    <li><a href="#">آرایشگاه</a></li>
                                    <li>
                                        <a href="#">آتلیه</a>
                                        <ul>
                                            <li><a href="#">آتلیه های ارزان</a></li>
                                            <li><a href="#">آتلیه شیک</a></li>
                                            <li><a href="#">آتلیه فشن</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#">لایه بندی صفحات</a></li>
                            <li><a href="#">برگزیده</a></li>
                            <li><a href="#">منتخب هفته</a></li>
                            <li><a href="#">تماس با ما</a></li>
                            <li><a href="#">درباره ما</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="TopLogo">
                        <img src="images/logo.png" class="center-block img-responsive" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--End TopMenu-->
</header>


@Html.Partial("_RegisterModal")

Bestinja.FronEnd.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>صفحه اصلی</title>


    <link href="~/Content/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap.css" rel="stylesheet">
    <link href="~/Content/css/bootstrap-rtl.css" rel="stylesheet">
    <link href="~/Content/css/select2.css" rel="stylesheet">
    <link href="~/Content/css/slicknav.css" rel="stylesheet">

    <link href="~/Content/css/style.css" rel="stylesheet">
    <link href="~/Content/css/media.css" rel="stylesheet">
    <link href="~/Content/css/login-register.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">

    <script src="~/Scripts/CustomJs/modernizr.min.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @RenderSection("styles",false)
</head>

<body>


    @Html.Partial("~/Views/Shared/_Header.cshtml")

    @RenderBody()
    @Html.Partial("~/Views/Shared/_Footer.cshtml")


    @Scripts.Render("~/bundles/jquery");

    <script src="~/Scripts/bootstrap.min.js"></script>
    @Scripts.Render("~/bundles/customJs");
    @Scripts.Render("~/bundles/jqueryval");
    @RenderSection("scriptsfilepond", false)
    @RenderSection("scripts", false)


    <script src="~/Scripts/CustomJs/login-register.js"></script>
    <script>

        $(function () {
            $('#MenuTop').slicknav({
                label: 'منو',
                duration: 1000
            });
        });
        $(document).ready(function () {

            $(".lstSelect").select2({
                dir: "rtl",
                width: '100%',
                placeholder: function () {
                    $(this).data('placeholder');
                }
            });
            $(function () {

                $(".parallax-demo").parallax();

            });
        });

    </script>

</body>

</html>

Bestinja.FronEnd.MVC/Views/Shared/_RegisterModal.cshtml
<div class="modal fade login" id="loginModal">
    <input type="hidden" id="userName"/>
    <div class="modal-dialog login animated">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <span class="errors"></span>
                <div class="box">
                    <div class="content">

                        <div class="division">
                            <div class="line l"></div>
                            <span id="title-login" class="hidden">ورود</span>
                            <span id="title-register"></span>
                            <div class="line r"></div>
                        </div>

                        <ul class="error"></ul>
                        <div class="form loginBox">
                            <form method="post" action="/home/login" accept-charset="UTF-8">
                                <input id="login-userName" class="form-control" type="text" placeholder="موبایل" name="userName">
                                <input id="password" class="form-control" type="password" placeholder="رمز عبور" name="password">
                         
                                
                                <button type="button"
                                        class="btn btn-primary btn-login"
                                        onclick="loginAjax(this)" 
                                       
                                        data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> در حال ارسال">
                                    ورود
                                </button>


                                <input class="btn btn-danger btn-forget" type="button" value="فراموش رمز عبور" onclick="forgetPassword()">

                            </form>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <div class="registerBox" style="display: none;">
                        <div class="form">
                            <div html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8">
                                <input id="register_userName" class="form-control" type="text" placeholder="شماره موبایل" name="userName">
                                <input id="register_password" class="form-control" type="password" placeholder="رمز عبور" name="password">
                                <input id="confirmPassword" class="form-control" type="password" placeholder="تکرار رمز عبور" name="password_confirmation">
                                <button type="submit" class="btn btn-primary btn-register next" onclick="Register(this)" id="register-btn" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> در حال ارسال">ثبت نام</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <div class="content confirmbox" style="display: none;">
                        <div class="form">
                            <div html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8">
                                <input id="confirmCode" class="form-control" type="text" placeholder="کد تایید" name="confirmCode">

                                <p>ارسال مجدد بعد از <span class="js-timeout"></span>.</p>

                                <button type="submit" onclick="confirmCode(this)" class="btn btn-primary btn-register" id="confirm-btn" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> در حال ارسال">ارسال</button>
                                <button type="submit" class="btn btn-default btn-register next" onclick="ConfirmAgain(this)" id="again-confirm-btn" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> در حال ارسال">ارسال مجدد</button>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="box">
                    <div class="content forgetBox" style="display: none;">
                        <div class="form">
                            <div html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8">
                                <input id="phonenumber" class="form-control" type="text" placeholder="شماره موبایل" name="confirmCode">

                                <button type="submit" class="btn btn-primary btn-register next" onclick="forgetPasswordBtn(this)" id="forget-btn" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> در حال ارسال">ارسال</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box">
                    <div class="content resetpasswordbox" style="display: none;">
                        <ul class="error"></ul>

                        <div class="form">
                            <div html="{:multipart=>true}" data-remote="true" accept-charset="UTF-8">
                                <input id="new-pass" class="form-control" type="password" placeholder="رمز عبور" name="confirmCode">
                                <input id="confirm-new-pass" class="form-control" type="password" placeholder="تکرار رمز عبور" name="confirmCode">

                                <button type="submit" class="btn btn-primary btn-register next" onclick="changePassword(this)" id="changepassword-btn" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> در حال ارسال">ارسال</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="forgot login-footer">
                    <span>
                        آیا
                        <a href="javascript: showRegisterForm();">ثبت نام</a>
                        کرده اید
                        ؟
                    </span>
                </div>
                <div class="forgot register-footer" style="display: none">
                    <span>قبلا ثبت نام کرده اید؟</span>
                    <a href="javascript: showLoginForm();">ورود</a>
                </div>
            </div>
        </div>
    </div>
</div>